### ISSUE TITLE
Grafana Dashboard Storage Claim not showing data

### ISSUE THREAD

**Issue by fforootd** [caos/boom#34]
<img width="1983" alt="Screenshot 2020-01-29 at 09 50 44" src="https://user-images.githubusercontent.com/9879976/73341418-e3982b80-427c-11ea-9b95-1f7be045855b.png">

**Comment by fforootd** [comment]
The dashboard is working now, but we need to change the calculation. This because the total space avail. is from the `disk` and not the `pv`.

<img width="1843" alt="Screenshot 2020-01-30 at 10 02 17" src="https://user-images.githubusercontent.com/9879976/73436479-e1040780-434a-11ea-8206-a8b31f8a878a.png">

**Comment by stebenz** [comment]
kube-state-metrics exposes metrics "kube_persistentvolumeclaim_resource_requests_storage_bytes" from de definition of the PVC and can be used as a workaround to calculate the free space.

But the result is that this dashboard gets a dependency that kube-state-metrics is deployed.

**Comment by stebenz** [comment]
included in #46

**Comment by fforootd** [comment]
now we get strange readings, but we get data :-)

![Screenshot 2020-01-30 at 14 57 22](https://user-images.githubusercontent.com/9879976/73455698-e07e6780-4370-11ea-9120-c9aaa55e7e3a.png)
