### ISSUE TITLE
Loki Retention

### ISSUE THREAD

**Issue by fforootd** [caos/boom#38]
Somehow Loki shows only data of around the last 30min

<img width="1979" alt="Screenshot 2020-01-29 at 09 54 39" src="https://user-images.githubusercontent.com/9879976/73341836-bdbf5680-427d-11ea-8f15-2b3d5f7ca513.png">

**Comment by fforootd** [comment]
The Logs are written to disk and survive a reboot.

**Comment by stebenz** [comment]
@fforootd logs are persistent, but grafana only lists with a maximum line count of 1000, which can be changed but not deactivated

**Comment by fforootd** [comment]
The latest version increased the retention to about `1h`, but somehow something is still wrong with the storage config 😁 

<img width="1830" alt="Screenshot 2020-01-30 at 09 51 16" src="https://user-images.githubusercontent.com/9879976/73433980-2eca4100-4346-11ea-838a-851a29b081c1.png">

**Comment by fforootd** [comment]
ignore my comment it is fixed and a `1000` line limit
