### ISSUE TITLE
Addon Folder in Cluster repository

### ISSUE THREAD

**Issue by fforootd** [caos/boom#53]
For things like `storageClasses` it would be a great improvement to define a folder in the source control which automatically will be applied bei either `boom` or `orbiter`.

Where should we place such a feature?

Inputs @eliobischof @stebenz

**Comment by fforootd** [comment]
Also @conblem feel free to comment

**Comment by fforootd** [comment]
IMHO it would be best to define a folder in the `boom.crd`. The content of this folder would then be applied in each iteration.

However there is a limit in this approach... it is not intended to use as a `fullblown reconciler`

Possible Use Cases:
- StorageClasses
- Ambassador Module Configs
- PersistentVolumes
- Argo CRD's for easy registration of `applications`

**Comment by stebenz** [comment]
that's why I would make the suggestion that we can add it in the boom-crd BUT only as argocd-application, as we already deploy a reconciler

**Comment by fforootd** [comment]
so you mean like a `cluster-addon` application which contains these resources?

**Comment by stebenz** [comment]
Exactly, as I would not use boom as a full fledged reconciler for yamls where we have no control over the contents, as testing of such functionality would also be too much at the moment.

**Comment by stebenz** [comment]
An additional use case would be the client_id + client_secret for the used IDP(s).
This could be stored in with Gopass and then reconciled with the custom Argocd which includes gopass.

**Comment by fforootd** [comment]
To summarise my point of view. I think we need to have to folders.
An `applications` folder for e.g `argo applications` and a `addons` folder for `storageClasses` and so on.

The we could separate the like `boom` applies `applications` and `orbiter` applies the `addons`.

**Comment by fforootd** [comment]
Minor change from latest discussion: `boom` should apply both folders 💯

**Comment by stebenz** [comment]
will be added in the next release, it is possible to configure the folders which should be applied before and after the reconciling
